controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    defaults:
        _format: json

register:
  path: /register
  controller: App\Controller\SecurityController::register
  methods: POST
